# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bytefall < Formula
  desc "Real-time network traffic visualization with Matrix-style aesthetics"
  homepage "https://github.com/sanif/bytefall"
  version "0.3.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/sanif/bytefall/releases/download/v0.3.0/bytefall_0.3.0_darwin_all.tar.gz"
  sha256 "b31ec600b5adc9078146e7710a0cc6a2c5d0a6068238674ad270cb1778947e2d"

  def install
    bin.install "bytefall"
  end

  def caveats
    <<~EOS
      ByteFall requires root privileges for packet capture.
      Run with: sudo bytefall

      Or use demo mode without privileges:
        bytefall -demo
    EOS
  end

  test do
    system "#{bin}/bytefall", "-version"
  end
end
