# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bytefall < Formula
  desc "Real-time network traffic visualization with Matrix-style aesthetics"
  homepage "https://github.com/sanif/bytefall"
  version "0.3.1"
  license "MIT"
  depends_on :macos

  url "https://github.com/sanif/bytefall/releases/download/v0.3.1/bytefall_0.3.1_darwin_all.tar.gz"
  sha256 "453150c5eab97c08bfd1375ce306933260c1e6973cbb371335dede8c5adcc031"

  def install
    bin.install "bytefall"
  end

  def caveats
    <<~EOS
      ByteFall requires root privileges for packet capture.
      Run with: sudo bytefall

      Or use demo mode without privileges:
        bytefall -demo
    EOS
  end

  test do
    system "#{bin}/bytefall", "-version"
  end
end
